apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-module-29493
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-module-29493
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
